In [45]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [8]:
df = pd.read_csv("C:/Users/SCIENCE/Documents/mart1.csv")
df

Item_Weight  Item_Visibility  Item_MRP  content  size
0         20.750         0.007565  107.8622      0.0     2
1          8.300         0.038428   87.3198      1.0     0
2         14.600         0.099575  241.7538      0.0     0
3          7.315         0.015388  155.0340      0.0     0
4            NaN         0.118599  234.2300      1.0     2
..           ...              ...       ...      ...   ...
444        8.850         0.054086  182.2292      0.0     2
445       15.600         0.035477  112.4518      1.0     1
446       16.750         0.060534  169.4106      0.0     2
447       14.150         0.034875  242.2828      0.0     2
448          NaN         0.066403  186.6924      0.0     2

[449 rows x 5 columns]

In [11]:
df.describe()


Item_Weight  Item_Visibility    Item_MRP     content        size
count   367.000000       449.000000  449.000000  445.000000  449.000000
mean     12.741635         0.065600  142.928974    0.330337    1.296214
std       4.810569         0.053494   60.737925    0.470864    0.905839
min       4.635000         0.000000   32.090000    0.000000    0.000000
25%       8.710000         0.024867   97.775200    0.000000    0.000000
50%      12.650000         0.052563  141.347000    0.000000    2.000000
75%      16.800000         0.097146  186.692400    1.000000    2.000000
max      21.350000         0.299544  264.691000    1.000000    2.000000

In [12]:
df.dropna()
df.isnull().sum()

Item_Weight        82
Item_Visibility     0
Item_MRP            0
content             4
size                0
dtype: int64

In [22]:
df["Item_Weight"]=df["Item_Weight"].replace([np.nan,0])
df["content"] = df["content"].replace([np.nan,0])
df.isnull().sum()

Item_Weight        0
Item_Visibility    0
Item_MRP           0
content            0
size               0
dtype: int64

In [23]:
y = df["Item_Weight"]
x = df.drop("Item_Weight", axis = 1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449 entries, 0 to 448
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Item_Weight      449 non-null    float64
 1   Item_Visibility  449 non-null    float64
 2   Item_MRP         449 non-null    float64
 3   content          449 non-null    float64
 4   size             449 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 17.7 KB


In [34]:
rf = RandomForestRegressor(n_estimators = 301)
rf.fit(x_train, y_train)
rf_pred = rf.predict(x_test)
rf_pred

array([10.23448505, 14.98629568, 14.28038206, 16.49667774, 15.5492691 ,
       16.31611296, 12.6422093 , 13.82262458, 11.73508306, 11.72186047,
       11.11815615, 14.53222591,  9.13963455, 16.59260797, 14.98318937,
       11.63362126, 12.89976744, 13.02034884, 12.4767608 , 12.28591362,
       11.54219269, 15.22345515, 13.79036545, 12.7091196 , 16.38769103,
       12.07380399, 13.62596346, 11.725     , 13.82224252, 12.09593023,
       12.03652824, 11.32425249, 11.44433555, 11.69297342,  7.82960133,
       10.95418605, 10.51343854, 11.52755814, 11.41043189, 10.95790698,
       10.01877076,  9.63561462, 15.02687708, 13.84277409, 11.76106312,
       16.30008306, 14.50463455, 14.04325581, 13.44046512, 11.95272425,
       11.81476744, 14.70139535, 12.31509967, 13.79684385,  9.07664452,
       10.74112957, 11.60539867, 11.15765781, 10.42219269, 10.75694352,
        8.61684385, 12.23207641,  9.53481728, 13.14594684, 16.64147841,
        9.95956811, 10.22928571, 15.20096346, 15.57966777,  8.69

In [31]:
print(mean_squared_error(rf_pred, y_test))

20.612421098610234


In [37]:
sv = SVR()
sv.fit(x_train, y_train)
sv.pred = sv.predict(x_test)
sv.pred

array([12.26173099, 12.47036903, 12.04412262, 13.13850969, 13.12602166,
       12.75870229, 12.88023189, 12.95522053, 12.64795701, 13.25047942,
       13.18691986, 12.98195125, 12.02974478, 12.87106834, 12.14116203,
       12.7603395 , 13.38201844, 13.1902379 , 12.03204869, 12.12696072,
       12.04098096, 12.75735292, 12.47437214, 12.06632944, 13.32214717,
       12.00069616, 12.86495916, 12.20015915, 12.65823289, 12.51403988,
       12.00186695, 12.31624935, 12.02620604, 12.90658003, 12.58165706,
       12.05079476, 12.26278972, 12.00214071, 12.00012907, 12.10269389,
       13.19711205, 12.29813586, 13.36028516, 13.03797215, 12.60037326,
       12.34757389, 12.62500521, 13.33171349, 12.08252949, 12.01419439,
       13.23084351, 12.7607183 , 12.01370587, 12.25107505, 12.19020023,
       12.0579556 , 12.15755857, 12.48705055, 12.35002322, 12.0720303 ,
       12.26554519, 12.93851236, 12.81769251, 12.71184043, 13.35066693,
       12.02257776, 11.99851273, 13.23025808, 12.72742406, 12.57

In [39]:
print(mean_squared_error(sv.pred, y_test))

21.95394695046845


In [42]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.pred = lr.predict(x_test)
lr.pred

array([12.54735976, 13.50617224, 11.06846104, 13.93360308, 13.6733748 ,
       12.78782897, 13.58581701, 13.54316107, 12.49826924, 13.06373183,
       12.83552434, 12.23115123, 12.01118579, 12.74266244, 12.55574767,
       12.30766257, 12.73594901, 12.41022814, 12.57542487, 11.67054934,
       12.9040501 , 13.01625942, 12.42424938, 12.47898658, 13.23977793,
       12.86463032, 12.91363197, 12.54742779, 13.62631761, 12.78602135,
       11.99762311, 12.19649779, 11.93273993, 12.97074666, 12.47015874,
       12.6513464 , 12.78361955, 12.65857555, 13.22489127, 12.34742931,
       12.16431179, 12.39327027, 11.11058569, 12.51292159, 13.3604786 ,
       13.32881534, 13.18009741, 12.93004878, 13.06207295, 12.74725499,
       13.1584343 , 12.84391912, 12.42572177, 13.21820131, 12.5627239 ,
       11.56657119, 11.05516889, 11.85854111, 12.33378254, 13.34225839,
       12.78923097, 12.9692242 , 12.48936131, 12.9991312 , 13.29085655,
       11.65183021, 11.773636  , 12.30885775, 13.8663787 , 12.89

In [43]:
print(mean_squared_error(lr.pred, y_test))

21.5881330082902


In [46]:
la = Lasso()
la.fit(x_train, y_train)
la.pred = la.predict(x_test)
la.pred

array([12.53696752, 12.63158969, 12.18762337, 12.93263989, 12.92554175,
       12.75421091, 12.80463873, 12.83874751, 12.70590586, 13.00794447,
       12.96162735, 12.85379733, 12.37445301, 12.80279677, 12.46991763,
       12.7549074 , 13.13822546, 12.96688352, 12.37741825, 12.46053966,
       12.19301441, 12.75363817, 12.63514985, 12.4136609 , 13.06322389,
       12.3029894 , 12.80009016, 12.50329662, 12.71016252, 12.65105322,
       12.26163654, 12.5645398 , 12.21175925, 12.81871124, 12.67934419,
       12.39590447, 12.53655184, 12.26831899, 12.29616099, 12.44334486,
       12.97128614, 12.55586942, 13.10882232, 12.8813696 , 12.68616151,
       12.57733198, 12.69638193, 13.07713934, 12.42644198, 12.23364858,
       12.99388307, 12.75506446, 12.34971111, 12.53057698, 12.49961269,
       12.40584408, 12.48028402, 12.63871002, 12.58029721, 12.41622156,
       12.53980899, 12.83333428, 12.77836898, 12.73247863, 13.09745643,
       12.21618406, 12.28025762, 12.99005318, 12.73899294, 12.67

In [47]:
print(mean_squared_error(la.pred, y_test))

21.786998124668603


In [48]:
rd = Ridge(alpha =1)
rd.fit(x_train, y_train)
rd.pred = rd.predict(x_test)
rd.pred

array([12.61749056, 13.34304471, 11.51508956, 13.69413135, 13.55987452,
       12.63661672, 13.46123062, 13.45513764, 12.86898155, 12.89004373,
       13.15420324, 12.40119776, 12.07415113, 12.6357911 , 12.39147096,
       12.39511298, 12.78374789, 12.5424051 , 12.35964705, 11.94144256,
       12.84193311, 12.75139883, 12.39979573, 12.32743134, 13.40362859,
       12.87169901, 12.7206724 , 12.80232577, 13.43900173, 12.78915647,
       12.01642058, 12.25323946, 12.16123357, 12.75783749, 12.64284823,
       12.80620763, 12.93627898, 12.75228468, 13.05005024, 12.27457013,
       12.42054482, 12.34842474, 11.95192797, 12.55554092, 13.29429308,
       13.22924566, 13.20806201, 12.85393837, 12.82684016, 12.78130229,
       12.93139293, 12.66524954, 12.27175381, 13.15244422, 12.40838201,
       11.86440043, 11.64043725, 12.51648899, 12.32948721, 13.16332641,
       12.54058954, 12.76366835, 12.69719662, 13.1332111 , 13.04481241,
       11.82176771, 11.91201919, 12.90179226, 13.57290721, 13.05

In [49]:
print(mean_squared_error(rd.pred, y_test))

21.771649985079367


In [51]:
xnew = [[0.007765, 307.8622, 0, 2]]
weight = rf.predict(xnew)
weight

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([14.31480066])