In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
Load Dataset and Do some Exploratory Analysis

In [2]:
df = pd.read_csv("C:/Users/SCIENCE/Downloads/Emails.csv.zip")
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


In [4]:
df.isnull()

text   spam
0     False  False
1     False  False
2     False  False
3     False  False
4     False  False
...     ...    ...
5723  False  False
5724  False  False
5725  False  False
5726  False  False
5727  False  False

[5728 rows x 2 columns]

In [ ]:
Doing Features Extraction from Email Messages

In [5]:
email= df.where((pd.notnull(df)))
email 

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [6]:
email.shape

(5728, 2)

In [7]:
x = email["text"]
y = email["spam"]

In [8]:
x

0       Subject: naturally irresistible your corporate...
1       Subject: the stock trading gunslinger  fanny i...
2       Subject: unbelievable new homes made easy  im ...
3       Subject: 4 color printing special  request add...
4       Subject: do not have money , get software cds ...
                              ...                        
5723    Subject: re : research and development charges...
5724    Subject: re : receipts from visit  jim ,  than...
5725    Subject: re : enron case study update  wow ! a...
5726    Subject: re : interest  david ,  please , call...
5727    Subject: news : aurora 5 . 2 update  aurora ve...
Name: text, Length: 5728, dtype: object

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.30, random_state =0)

In [10]:
x_train

3284    Subject: confirming your attendance - oct . 19...
4031    Subject: year end 2000 performance feedback  n...
3031    Subject: re : mec  steve ,  i spoke with david...
227     Subject: reply a . s . a . p  united trust ban...
3414    Subject: re : high - end desktop computing ?  ...
                              ...                        
4931    Subject: interview schedule - iris mack  attac...
3264    Subject: welcome to pjm - customer - info  - -...
1653    Subject: request submitted : access request fo...
2607    Subject: houston trip  hi jaideep !  my first ...
2732    Subject: cv - keith baggerly  i have attached ...
Name: text, Length: 4009, dtype: object

In [11]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(5728,)
(4009,)
(1719,)


In [12]:
feature_extraction = TfidfVectorizer(min_df =1, stop_words = "english")
x_train_features = feature_extraction.fit_transform(x_train)
x_test_features = feature_extraction.transform(x_test)
x_train = y_train.astype("int")
y_test = y_test.astype("int")
                                               
                                                   

In [13]:
print(x_train_features)

  (0, 10854)	0.01640883184386347
  (0, 29759)	0.025889281535986852
  (0, 11132)	0.03986067746228503
  (0, 14836)	0.014025453985224577
  (0, 30661)	0.019124897683063104
  (0, 822)	0.03704070864500693
  (0, 12307)	0.01555044180210418
  (0, 2493)	0.03704070864500693
  (0, 1992)	0.05941469521173039
  (0, 647)	0.031270254237875515
  (0, 2152)	0.07408141729001386
  (0, 9786)	0.03636782848071048
  (0, 26033)	0.03104625665413103
  (0, 470)	0.024459340821632435
  (0, 24492)	0.012921985383432625
  (0, 18293)	0.015142429311335191
  (0, 28251)	0.028011825006954653
  (0, 27112)	0.023846095861083664
  (0, 7181)	0.043353526443859564
  (0, 5758)	0.03704070864500693
  (0, 26138)	0.03704070864500693
  (0, 19177)	0.022396432554412316
  (0, 4392)	0.05146843916279556
  (0, 6698)	0.04131034076895638
  (0, 24874)	0.043353526443859564
  :	:
  (4008, 5066)	0.4412947331386972
  (4008, 4670)	0.20377579803413728
  (4008, 16722)	0.3489015447109839
  (4008, 23019)	0.11976796431626925
  (4008, 15497)	0.1144777918860

In [14]:

lr = LogisticRegression()
lr.fit(x_train_features, y_train)   
pred = lr.predict(x_train_features)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:

sv =SVC()
sv.fit(x_train_features, y_train)
pre =sv.predict(x_train_features)
pre

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
print(accuracy_score(pred, y_train))

0.9965078573210276


In [21]:
print(accuracy_score(pre, y_train))

1.0


In [23]:
print(classification_report(pred, y_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3056
           1       0.99      1.00      0.99       953

    accuracy                           1.00      4009
   macro avg       0.99      1.00      1.00      4009
weighted avg       1.00      1.00      1.00      4009



In [24]:
print(classification_report(pre, y_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3046
           1       1.00      1.00      1.00       963

    accuracy                           1.00      4009
   macro avg       1.00      1.00      1.00      4009
weighted avg       1.00      1.00      1.00      4009



Predicting if the message is spam or not using the Above Model

In [32]:
xnew = ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]
xnew = feature_extraction.transform(xnew)
predi = lr.predict(xnew)
predi

array([1], dtype=int64)